// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from "@hey-api/client-axios";
import type {
  GetTracksTracksGetData,
  GetTracksTracksGetError,
  GetTracksTracksGetResponse,
  SearchTracksTracksSearchGetData,
  SearchTracksTracksSearchGetError,
  SearchTracksTracksSearchGetResponse,
  GetTrackTracksTrackIdGetData,
  GetTrackTracksTrackIdGetError,
  GetTrackTracksTrackIdGetResponse,
} from "./types.gen";

export const client = createClient(createConfig());

client.setConfig({
  baseURL: process.env.NEXT_PUBLIC_BASE_URL,
});

/**
 * Get Tracks
 */
export const getAllTracks = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<GetTracksTracksGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTracksTracksGetResponse,
    GetTracksTracksGetError,
    ThrowOnError
  >({
    ...options,
    url: "/tracks/",
  });
};

/**
 * Search Tracks
 */
export const searchTracks = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SearchTracksTracksSearchGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SearchTracksTracksSearchGetResponse,
    SearchTracksTracksSearchGetError,
    ThrowOnError
  >({
    ...options,
    url: "/tracks/search",
  });
};

/**
 * Get Track
 */
export const getTrackById = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetTrackTracksTrackIdGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetTrackTracksTrackIdGetResponse,
    GetTrackTracksTrackIdGetError,
    ThrowOnError
  >({
    ...options,
    url: "/tracks/{track_id}",
  });
};
