// This file is auto-generated by @hey-api/openapi-ts

export type Author = {
    id: string;
    name: string;
    genres: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Track = {
    id: string;
    title: string;
    authors: Array<Author>;
    duration: number;
    source: string;
    thumbnail: string;
};

export type Tracks = {
    tracks: Array<Track>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetTracksTracksGetData = {
    query?: {
        limit?: number;
        offset?: number;
    };
};

export type GetTracksTracksGetResponse = (Tracks);

export type GetTracksTracksGetError = (HTTPValidationError);

export type SearchTracksTracksSearchGetData = {
    query: {
        limit?: number;
        offset?: number;
        query: string;
    };
};

export type SearchTracksTracksSearchGetResponse = (Tracks);

export type SearchTracksTracksSearchGetError = (HTTPValidationError);

export type GetTrackTracksTrackIdGetData = {
    path: {
        track_id: string;
    };
};

export type GetTrackTracksTrackIdGetResponse = (Track);

export type GetTrackTracksTrackIdGetError = (HTTPValidationError);